
#---------------------------------------#
####           APPENDIX              ####
#---------------------------------------#

tinhthanh = data.frame(tinhthanh=c(), khuvuc=c())

tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Hà Nội", khuvuc = "MB"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Hà Giang", khuvuc = "MB"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Cao Bằng", khuvuc = "MB"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Bắc Kạn", khuvuc = "MB"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Tuyên Quang", khuvuc = "MB"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Lào Cai", khuvuc = "MB"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Điện Biên", khuvuc = "MB"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Lai Châu", khuvuc = "MB"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Sơn La", khuvuc = "MB"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Yên Bái", khuvuc = "MB"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Hòa Bình", khuvuc = "MB"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Thái Nguyên", khuvuc = "MB"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Lạng Sơn", khuvuc = "MB"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Quảng Ninh", khuvuc = "MB"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Bắc Giang", khuvuc = "MB"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Phú Thọ", khuvuc = "MB"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Vĩnh Phúc", khuvuc = "MB"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Bắc Ninh", khuvuc = "MB"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Hải Dương", khuvuc = "MB"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Hải Phòng", khuvuc = "MB"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Hưng Yên", khuvuc = "MB"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Thái Bình", khuvuc = "MB"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Hà Nam", khuvuc = "MB"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Nam Định", khuvuc = "MB"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Ninh Bình", khuvuc = "MB"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Thanh Hóa", khuvuc = "MT"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Nghệ An", khuvuc = "MT"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Hà Tĩnh", khuvuc = "MT"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Quảng Bình", khuvuc = "MT"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Quảng Trị", khuvuc = "MT"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Thừa Thiên Huế", khuvuc = "MT"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Đà Nẵng", khuvuc = "MT"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Quảng Nam", khuvuc = "MT"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Quảng Ngãi", khuvuc = "MT"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Bình Định", khuvuc = "MT"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Phú Yên", khuvuc = "MT"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Khánh Hòa", khuvuc = "MT"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Ninh Thuận", khuvuc = "MT"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Bình Thuận", khuvuc = "MT"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Kon Tum", khuvuc = "MT"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Gia Lai", khuvuc = "MT"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Đắk Lắk", khuvuc = "MT"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Đắk Nông", khuvuc = "MT"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Lâm Đồng", khuvuc = "MT"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Bình Phước", khuvuc = "MN"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Tây Ninh", khuvuc = "MN"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Bình Dương", khuvuc = "MN"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Đồng Nai", khuvuc = "MN"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Vũng Tàu", khuvuc = "MN"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "TP. Hồ Chí Minh", khuvuc = "MN"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Long An", khuvuc = "MN"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Tiền Giang", khuvuc = "MN"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Bến Tre", khuvuc = "MN"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Trà Vinh", khuvuc = "MN"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Vĩnh Long", khuvuc = "MN"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Đồng Tháp", khuvuc = "MN"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "An Giang", khuvuc = "MN"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Kiên Giang", khuvuc = "MN"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Cần Thơ", khuvuc = "MN"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Hậu Giang", khuvuc = "MN"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Sóc Trăng", khuvuc = "MN"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Bạc Liêu", khuvuc = "MN"))
tinhthanh = rbind(tinhthanh, data.frame(tinhthanh = "Cà Mau", khuvuc = "MN"))

tinhthanh$tinhthanh = tinhthanh$tinhthanh %>% stri_trans_tolower() %>% removePunctuation() %>% stripWhitespace()

